### ISSUE TITLE
It does not work in RC2 projects

### ISSUE THREAD

**Issue by xatabhk** [serilog/serilog-extensions-logging#27]

**Comment by khellang** [comment]
RC2 hasn't been released yet :smile:

**Comment by jbergs** [comment]
Now that RC2 is out, is there any estimate on when it will be supported?

**Comment by merbla** [comment]
@jbergs @xatabhk once this gets out, extensions will follow... 

https://github.com/serilog/serilog/pull/742

**Comment by nblumhardt** [comment]
Done - https://www.nuget.org/packages/Serilog.Extensions.Logging/1.0.0-rc2-10096

**Comment by xatabhk** [comment]
It still does not work for me. 
![serilog_nuget_error](https://cloud.githubusercontent.com/assets/6814395/15320817/1cc8203c-1c65-11e6-830c-42cb9e5d4fcc.png).
Project.json:
[project.txt](https://github.com/serilog/serilog-extensions-logging/files/268034/project.txt)

**Comment by SimonOrdo** [comment]
Package Serilog.Extensions.Logging 1.0.0-rc2-10096 is not compatible with net452 (.NETFramework,Version=v4.5.2). Package Serilog.Extensions.Logging 1.0.0-rc2-10096 supports: netstandard1.3 (.NETStandard,Version=v1.3)

    One or more packages are incompatible with .NETFramework,Version=v4.5.2.

**Comment by nblumhardt** [comment]
Thanks @xatabhk @SimonOrdo - this is: https://github.com/serilog/serilog-extensions-logging/issues/31
